config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :pictures do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :title, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  skip_before_action :login_required, only: [:new, :create, :show, :edit, :confirm, :destroy]

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: 'ブログを作成しました'
      else
        render :new
      end
    end
  end

  def index
    @pictures = Picture.all
  end

  def show
  end

  def edit
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "ブログを編集しました！"
    else
      render :edit
    end
  end

  def destroy
 		@picture.destroy
 		redirect_to pictures_path, notice:"ブログを削除しました！"
 	end

  private
  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    # ログアウトの処理
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
  	if action_name == 'new' || action_name == 'create'
  	  confirm_pictures_path
  	elsif action_name == 'edit'
  	  picture_path
  	end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FbCloneApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <% if logged_in? %>
      <%= link_to "ブログ一覧へ", pictures_path %>
      <%= link_to "プロファイル", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "新規登録", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
  </header>

  <body>
    <% flash.each do |key, value| %>
     <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>

  <footer>
    <p>© 2021 fb_clone_app, Inc.</p>
  </footer>

</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <%= form.submit %>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
  <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
<p>タイトル:<%= @picture.title %></p>
<p>本文:<%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
  <% end %>

app/views/pictures/edit.html.erb
<div class="users_h1_box"><h2>ブログを編集する</h2></div>
<%= render 'form' %>

<%= link_to '詳細', @picture %> |
<%= link_to '戻る', pictures_path %>

app/views/pictures/index.html.erb
<div class="users_h1_box"><h1>ブログ一覧</h1></div>
<p><%= notice %></p>
<table>
  <tr>
    <th>投稿者</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>画像</th>
  </tr>
<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.user.name %></td>
    <td><%= picture.title %></td>
    <td><%= picture.content %></td>
    <td><%= picture.image %></td>
    <td><%= link_to '詳細を確認する', picture_path(picture.id) %></td>
    <td><%= link_to "ブログを編集する", edit_picture_path(picture.id) %></td>
    <td><%= link_to 'ブログを削除する', picture_path(picture.id), method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to '新しくブログを投稿する', new_picture_path %>

app/views/pictures/new.html.erb
<div class="users_h1_box"><h2>ブログを作成する</h2></div>
<%= render 'form' %>

<%= link_to "戻る", pictures_path%>

app/views/pictures/show.html.erb
<div class="users_h1_box"><h1>ブログ詳細画面</h1></div>
<p>投稿者<%= @picture.user.name %></p>
<p>タイトル: <%= @picture.title %></p>
<p>内容: <%= @picture.content %></p>
<p id="notice"><%= notice %></p>
<% if @picture.image.url %>
<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>
<% end %>
<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>
<%= link_to "一覧へ", pictures_path %>

app/views/users/new.html.erb
<div class="users_h1_box"><h1>FBクローン新規登録</h1></div>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="login">
  <div class="login-triangle"></div>
  <h2 class="login-header">Log in</h2>
  <%= form_with(model: @user, local: true) do |f| %>
  <form class="login-container">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Create my account" %>
  </form>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<%= link_to "一覧へ", pictures_path %>